// Shared field set for service pages that use the Storytelling layout: hero →
// photo+text intro → partner bar → collaboration → final CTA (rendered by
// SimpleServicePage). Each page is its own singleton document type, so it
// appears as its own pinned entry in Studio's Services folder, and all of
// them share this field shape, defined once here.
export function simpleServicePageSchema(name: string, title: string, defaultPageTitle: string) {
  return {
    name,
    title,
    type: 'document',
    fieldsets: [
      {
        name: 'hero',
        title: 'Hero',
        options: { collapsible: true, collapsed: false },
      },
    ],
    fields: [
      {
        name: 'title',
        title: 'Page Title (used to pick this page in Navigation/Footer)',
        type: 'string',
        initialValue: defaultPageTitle,
      },
      {
        name: 'slug',
        title: 'URL Slug',
        type: 'slug',
        options: { source: 'title' },
        validation: (Rule: any) => Rule.required(),
      },
      {
        name: 'headline',
        title: 'Hero Headline (H1)',
        description: 'Type <br> to force a line break.',
        type: 'localeString',
        fieldset: 'hero',
      },
      {
        name: 'heroTagline',
        title: 'Hero: Text on the blue bar below the headline',
        description: 'Optional — the same blue bar as the standard Hero. Leave empty to hide it.',
        type: 'localeString',
        fieldset: 'hero',
      },
      {
        name: 'intro',
        title: 'Intro (photo + text)',
        description: 'One block = one photo+text section, like on Storytelling. Add a second block to stack two sections (like on Word & PDF) — alternating: 1. photo on the left / navy text on the right, 2. gray text on the left / photo on the right, and so on.',
        type: 'array',
        of: [
          {
            type: 'object',
            name: 'introBlock',
            fields: [
              {
                name: 'headline',
                title: 'Heading above the text (optional)',
                type: 'localeString',
              },
              {
                name: 'image',
                title: 'Photo',
                type: 'image',
                options: { hotspot: true },
                fields: [
                  { name: 'alt', title: 'Alt text', type: 'string' },
                  {
                    name: 'aiGenerated',
                    title: 'This image was generated by AI',
                    description: 'Shows an "AI-generated" / "KI-generiert" badge (depending on the page language) in the bottom-left corner of the image.',
                    type: 'boolean',
                    initialValue: false,
                  },
                ],
              },
              {
                name: 'body',
                title: 'Text (two paragraphs — leave a blank line between them)',
                type: 'localeRichText',
              },
            ],
            preview: {
              select: { title: 'headline.en', media: 'image' },
            },
          },
        ],
      },
      {
        name: 'products',
        title: 'Products / Services (text, no links)',
        description: 'Short product/service names shown as plain text (not links) — for SEO. Any number of items, in two columns.',
        type: 'array',
        of: [{ type: 'localeString' }],
      },
      {
        name: 'partnerBar',
        title: 'Partner Bar',
        type: 'object',
        fields: [
          {
            name: 'text',
            title: 'Text',
            type: 'localeRichText',
          },
        ],
      },
      {
        name: 'collaboration',
        title: 'Besser zusammenarbeiten',
        type: 'object',
        fields: [
          {
            name: 'headline',
            title: 'Headline (H2)',
            type: 'localeString',
          },
          {
            name: 'body',
            title: 'Body text',
            type: 'localeRichText',
          },
          {
            name: 'items',
            title: 'Linked services (exactly 3)',
            description: 'Choose 3 services — each will appear as a link to its own page, with an arrow at the end (like the services list on the homepage).',
            type: 'array',
            validation: (Rule: any) => Rule.min(3).max(3).error('Exactly 3 services required'),
            of: [
              {
                type: 'reference',
                to: [{ type: 'service' }],
              },
            ],
          },
        ],
      },
      {
        name: 'seo',
        title: 'SEO',
        type: 'seo',
      },
    ],
  }
}
