import { localeValidation } from '../lib/textRules'

export default {
  name: 'textAndImageSlider',
  title: 'Text and Image Slider',
  type: 'document',
  fields: [
    {
      name: 'sectionName',
      title: 'Section Name',
      type: 'string',
    },
    {
      name: 'headline',
      title: 'Headline',
      type: 'localeString',
    },
    {
      name: 'body',
      title: 'Body',
      type: 'object',
      validation: localeValidation,
      fields: [
        { name: 'en', type: 'text', title: 'English' },
        { name: 'de', type: 'text', title: 'Deutsch' },
      ],
    },
    {
      name: 'images',
      title: 'Images (slider)',
      description: 'Images shown in the slider on the left side of the section.',
      type: 'array',
      validation: (Rule: any) => Rule.min(1).error('At least 1 image required'),
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            { name: 'alt', title: 'Alt text', type: 'string' },
            {
              name: 'aiGenerated',
              title: 'This image was generated by AI',
              description: 'Shows an "AI-generated" / "KI-generiert" badge in the bottom-left corner when this image is active in the slider.',
              type: 'boolean',
              initialValue: false,
            },
          ],
        },
      ],
    },
    {
      name: 'buttonText',
      title: 'Button Text',
      type: 'localeString',
    },
    {
      name: 'buttonPage',
      title: 'Link: Page',
      description: 'Choose an existing page instead of typing a URL manually.',
      type: 'reference',
      to: [{ type: 'contact' }, { type: 'about' }, { type: 'howWeWork' }, { type: 'homepage' }, { type: 'portfolio' }],
    },
    {
      name: 'buttonHref',
      title: 'Link: Manual URL',
      description: 'Use only if no page was selected above (e.g. an external link).',
      type: 'string',
    },
  ],
}
