import { localeValidation } from '@/sanity/lib/textRules'

export default {
  name: 'textAndImageSliderServices',
  title: 'Text and Image Slider (Service Links)',
  type: 'document',
  fields: [
    {
      name: 'sectionName',
      title: 'Section Name',
      type: 'string',
    },
    {
      name: 'headline',
      title: 'Headline',
      type: 'localeString',
    },
    {
      name: 'body',
      title: 'Body',
      type: 'object',
      validation: localeValidation,
      fields: [
        { name: 'en', type: 'text', title: 'English' },
        { name: 'de', type: 'text', title: 'Deutsch' },
      ],
    },
    {
      name: 'images',
      title: 'Images (slider)',
      description: 'Images shown in the slider on the left side of the section.',
      type: 'array',
      validation: (Rule: any) => Rule.min(1).error('At least 1 image required'),
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            { name: 'alt', title: 'Alt text', type: 'string' },
            {
              name: 'aiGenerated',
              title: 'This image was generated by AI',
              description: 'Shows an "AI-generated" / "KI-generiert" badge in the bottom-left corner when this image is active in the slider.',
              type: 'boolean',
              initialValue: false,
            },
          ],
        },
      ],
    },
    {
      name: 'services',
      title: 'Related Services (exactly 3)',
      description: 'Links to 3 services shown instead of a button (name + arrow).',
      type: 'array',
      validation: (Rule: any) => Rule.length(3).error('Exactly 3 services required'),
      of: [
        {
          type: 'reference',
          to: [{ type: 'service' }],
        },
      ],
    },
  ],
  preview: {
    select: { title: 'sectionName', subtitle: 'headline.en' },
  },
}
