export default {
  name: 'videoSection',
  title: 'Video Section',
  type: 'document',
  fields: [
    {
      name: 'sectionName',
      title: 'Section Name',
      type: 'string',
      description: 'e.g. "Showreel"',
    },
    {
      name: 'video',
      title: 'Video (MP4)',
      type: 'file',
      options: { accept: 'video/mp4' },
    },
    {
      name: 'aiGenerated',
      title: 'This video was generated by AI',
      description: 'Shows an "AI-generated" / "KI-generiert" badge (depending on the page language) in the bottom-left corner.',
      type: 'boolean',
      initialValue: false,
    },
  ],
}
